# Generated by Django 4.2.4 on 2023-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='time',
            field=models.CharField(default=5, max_length=4),
        ),
    ]
