# Generated by Django 4.2.4 on 2023-08-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_carouselitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselitem',
            old_name='order',
            new_name='sequence',
        ),
    ]
