# Generated by Django 4.2.4 on 2023-08-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_rename_order_carouselitem_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='time',
            field=models.CharField(default='', max_length=4),
        ),
    ]
